### ISSUE TITLE
Bag vanishes on place

### ISSUE THREAD

**Issue by FabioZumbi12** [Darkona/AdventureBackpack2#86]
On player try to place the Bag on a non placeable location(protected by plugin), the BAG vanishes :/

Using KCauldron 1.7.10 and latest dev version of MOD(adventurebackpack-1.7.10-0.8-dev.jar)

*Testing place other mods itens and machines dont vanish, only deny, as spected!

**Comment by Darkona** [comment]
Working on it.

**Comment by Darkona** [comment]
Might be fixed for next version. Please test when it's out

**Comment by Darkona** [comment]
Apparently fixed in Beta-0.8c Needs confirmation

**Comment by FabioZumbi12** [comment]
The bug stills. I've recorded on this video to you get exactly what happens: http://areaz12server.net.br/dowload/bugadventurepack.mp4
